[es_nodes]
es-node1 es_ip=172.17.0.2
es-node2 es_ip=172.17.0.3
es-node3 es_ip=172.17.0.4

[es_nodes:vars]
ansible_connection=docker
ansible_user=root
ansible_python_interpreter=/usr/bin/python3
ansible_remote_tmp=/tmp/.ansible-tmp
