---
- name: Base OS setup for all ES nodes
  hosts: es_nodes
  become: true
  roles:
    - role: common
      tags: common

- name: Install Elasticsearch on all nodes
  hosts: es_nodes
  become: true
  roles:
    - role: elasticsearch
      tags: elasticsearch

- name: Generate CA and certificates
  hosts: es_nodes
  become: true
  roles:
    - role: certificates
      tags: certificates

- name: Start cluster and set up passwords
  hosts: es_nodes
  become: true
  roles:
    - role: security
      tags: security
